### ISSUE TITLE
[BUG]not able to install on 11.5.26 error in 

### ISSUE THREAD

**Issue by mrkbr** [CPS-IT/personio-jobs#108]
### TYPO3 version

11.5.26

### PHP version

7.4.33

### Extension version

0.5.4

### Composer mode

- [ ] I'm running TYPO3 in composer mode.

### Operating system

lamp webserver - standard shared hosting

### Current behavior

If I install it on non-composer environment, the whole system will crash with this message:

The file "[pathshortened_by_me]/public/typo3conf/ext/personio_jobs/Configuration//Services.yaml" does not contain valid YAML: The constant "CPSIT\Typo3PersonioJobs\Domain\Model\Job::TABLE_NAME" is not defined at line 43 (near "!php/const CPSIT\Typo3PersonioJobs\Domain\Model\Job::TABLE_NAME").

PHP Version maybe?

Best,
Mario

### Steps to reproduce

Just install via extension manager.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mrkbr** [comment]
Changed the staging instance to 11.5.31, PHP8 - same problem. When I activate the extension, this is the error output:

 Fatal error: Cannot use 'final' as constant modifier in /var/www/vhosts/job-ifb.de/httpdocs/mainframe_staging/public/typo3conf/ext/personio_jobs/Classes/Domain/Model/Job.php on line 43

Frontend shows the same error like above.

**Comment by eliashaeussler** [comment]
Hi @mrkbr, thanks for your issue.

The extension requires at least PHP 8.1. Unfortunately, I forgot to add this requirement to `ext_emconf.php`. Sorry for that – will add it later. You most probably get those issues because of an unsupported PHP version. Can you check if the errors are gone when switching to PHP 8.1?

**Comment by mrkbr** [comment]
Yes that was the only problem. It already works on my dev system. Import works, too. Thanks for you info and for the change in the new release.
