### ISSUE TITLE
[FEATURE] Availability of "Career Page" data

### ISSUE THREAD

**Issue by minapok** [CPS-IT/personio-jobs#43]
### Is your feature request related to a problem?

In Personio, there are various fields in the settings in the "Recruiting" > "Career page" area that can be displayed on Personio job detail pages (e.g. RTE field "About us"). So far, this data has not been included in the import.

### Describe the solution you'd like

An import of this data would be desirable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @minapok, thanks for your feature request.

Do you know if such data is currently exposed through any API? I couldn't find any information about this. It seems like the XML feed only provides available positions (see https://developer.personio.de/reference/get_xml for reference).

**Comment by minapok** [comment]
You're right, it seems that there is no data provided by the API. I close the issue.
