### ISSUE TITLE
[BUG] Eval Required 

### ISSUE THREAD

**Issue by Ranunzel** [CPS-IT/personio-jobs#44]
### TYPO3 version

12.4.0

### PHP version

8.1

### Extension version

0.5.0

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Linux

### Current behavior

tx_personiojobs_domain_model_job_description -> Bodytext has wrong eval. 
**Current:**
               eval' => 'required',

**Need** 
               'required' => true,

see changelog:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97035-RequiredOptionInEvalKeyword.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
@Ranunzel Thanks a lot for the issue! I'm currently a bit busy, but will try to have a look at it in the next days. Feel free to provide a PR :)

**Comment by Ranunzel** [comment]
Moin, falls noch Erläuterungen oder Beispiele benötigt werden, einfach melden 😊

Am 30. Mai 2023 10:31:52 MESZ schrieb "Elias Häußler" ***@***.***>:

**Comment by eliashaeussler** [comment]
Hi @Ranunzel, this is now resolved with `0.5.1`.
