### ISSUE TITLE
[FEATURE] Enhance EmploymentType

### ISSUE THREAD

**Issue by Ranunzel** [CPS-IT/personio-jobs#46]
### Is your feature request related to a problem?

The EmploymentType need more values, f.e. "temporary"

### Describe the solution you'd like

The EmploymentType need more values, f.e. "temporary"

### Additional context

namespace CPSIT\Typo3PersonioJobs\Enums\Job;

/**
 * EmploymentType
 *
 * @author Elias Häußler <e.haeussler@familie-redlich.de>
 * @license GPL-2.0-or-later
 */
enum EmploymentType: string
{
    case Freelance = 'freelance';
    case Intern = 'intern';
    case Permanent = 'permanent';
    case Trainee = 'trainee';
    case WorkingStudent = 'working_student';
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
@Ranunzel Thanks a lot for the issue! I'm currently a bit busy, but will try to have a look at it in the next days. Feel free to provide a PR :)

**Comment by eliashaeussler** [comment]
Hi @Ranunzel, this is now resolved with `0.5.1`.
