### ISSUE TITLE
[BUG] Import failed

### ISSUE THREAD

**Issue by Ranunzel** [CPS-IT/personio-jobs#81]
### TYPO3 version

12.4.5

### PHP version

8.1

### Extension version

0.5.3

### Composer mode

- [ ] I'm running TYPO3 in composer mode.

### Operating system

Linux

### Current behavior

The XmlToArray failes to convert when only 1 Jobs gets imported. The nesting is wrong,

In PersonioApiService line 71

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by garbast** [comment]
In addition it would be good to remove the final from the class, to be able to fix it with an XClass, while waiting for a fix.

**Comment by eliashaeussler** [comment]
Hi @garbast, if you have a working XCLASS in place, feel free to submit a PR, and I'll be happy to merge it. Otherwise, I'll try to have a look at it next week.

**Comment by Ranunzel** [comment]
@eliashaeussler   Fixed by @garbast  https://github.com/garbast/personio-jobs.git

**Comment by eliashaeussler** [comment]
@Ranunzel @garbast This is now fixed and covered with tests. I just released `0.5.3` containing this fix.
